[package]
name = "nexus-pstruct"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true


[dependencies]
bit-ext = { path = "../bit-ext"}
arbitrary-int = "2.0.0"
num = "0.4.3"
quote = "1.0.42"
syn = {version = "2.0.111", features = ["full"]}
funty = "2.0.0"
